name: test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: coverage profile
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.22' ]
        os: [ ubuntu-latest, macos-latest, self-hosted-linux-arm64]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version-file: go.mod
        - name: generate test coverage
          run: make install-go-test-coverage && make cover.out
        - name: check test coverage
          uses: vladopajic/go-test-coverage@v2
          with:
            config: .testcoverage.yml
